name: Checks
permissions:
  contents: read
on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
        - env:
            TOXENV: bandit
        - env:
            TOXENV: black
        - env:
            TOXENV: flake8
        - env:
            TOXENV: typing
        - env:
            TOXENV: pylint
        - env:
            TOXENV: docs
          python-version: "3.14"

    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: ${{ matrix.python-version || '3.11' }}

    - name: Run check
      env: ${{ matrix.env }}
      run: |
        pip install -U pip
        pip install -U tox
        tox
