name: Checks
on: [push, pull_request, workflow_dispatch]

jobs:
  checks:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        include:
        - env:
            TOXENV: bandit
        - env:
            TOXENV: black
        - env:
            TOXENV: flake8
        - env:
            TOXENV: typing
        - env:
            TOXENV: pylint

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run check
      env: ${{ matrix.env }}
      run: |
        pip install -U pip
        pip install -U tox
        tox
